.TH upnp-router-control 1 "2 Dec 2009"
.SH NAME
upnp-router-control \- manage UPnP IGD compliant routers
.SH SYNOPSIS
.B upnp-router-control
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B upnp-router-control
command.
.PP
\fBupnp-router-control\fP allow to see some params of the IGD compliant
routers like the download speed and manage port forwarding trough UPnP protocol.
.SH OPTIONS
A summary of options is included below.
.TP
\fB\-i\fR \fIinterface\fR, \fB\-\-if=\fR \fIinterface\fR
Use the specified network interface (autodetect if omitted). 
.TP
\fB\-p\fR \fIport\fR, \fB\-\-port=\fR \fIport\fR
Use the specified source port (autoselected if omitted).
.TP
.B \-h,  --help
Show summary of options and exit.
.TP
.B \--version
Show program's version number and exit.
.TP
.B \--debug
Enable debug mode.
.SH AUTHOR
Written by Daniele Napolitano <dnax88@gmail.com>.
.PP
.\" Copyright 2009 Daniele Napolitano
.\" You may copy this manual page under the terms of the version 2 of
.\" the GNU General Public License.
