#! /usr/bin/env python
# encoding: utf-8
# Daniele Napolitano, 2009

# Launcher
if bld.env['INTLTOOL']:
    obj			        = bld.new_task_gen('intltool_in')
    obj.source		    = 'upnp-router-control.desktop.in'
    obj.install_path	= '${DATADIR}/applications'
    obj.podir           = '../po'
    obj.flags		    = ['-d', '-u', '-c' ]

# Icons
bld.install_as('${DATADIR}/icons/hicolor/scalable/apps/upnp-router-control.svg', 'apps_scalable_upnp-router-control.svg')

for i in ["16x16", "22x22", "24x24", "32x32", "48x48"]:
	bld.install_as('${DATADIR}/icons/hicolor/%s/apps/upnp-router-control.png' % i, 'apps_%s_upnp-router-control.png' % i)

# Glade file
bld.install_as('${DATADIR}/upnp-router-control/upnp-router-control.glade', 'upnp-router-control.glade')

# Man page
bld.install_as('${DATADIR}/man/man1/upnp-router-control.1', 'upnp-router-control.1')
