#! /usr/bin/env python
# encoding: utf-8
# Daniele Napolitano, 2009

# Icons
bld.install_files('${DATADIR}/icons/hicolor/scalable/apps', 'upnp-port-mapper.svg')
bld.install_files('${DATADIR}/upnp-port-mapper', 'upnp-port-mapper.svg')

# Glade file
bld.install_files('${DATADIR}/upnp-port-mapper', 'upnp-port-mapper.glade')
