#! /usr/bin/env python
# encoding: utf-8
# Daniele Napolitano, 2009

obj = bld.new_task_gen('cc', 'program')
obj.includes= ['.', '../']
obj.env['CPPFLAGS'] = ['-Wall', '-g', '-O2']
#obj.env['CPPFLAGS'] = ['-march=pentium4', '-pipe', '-fomit-frame-pointer']
#obj.env['LINKFLAGS'] = ['-export-dynamic']
obj.find_sources_in_dirs('.')
obj.uselib = 'GTK GSSDP GUPNP LIBCURL'
obj.target = 'upnp-router-control'
