#! /usr/bin/env python
# encoding: utf-8
# Daniele Napolitano, 2009

obj = bld.new_task_gen('cc', 'program')
obj.includes='.'
obj.env['CPPFLAGS'] = '-g -Wall'
#obj.env['CPPFLAGS'] = '-march=pentium4 -O2 -pipe -fomit-frame-pointer'
#obj.env['LINKFLAGS'] = '-ljsw -export-dynamic'
obj.find_sources_in_dirs('.')
obj.uselib = 'GTK GLADE GUPNP'
obj.target = 'upnp-port-mapper'
